airbyte_transformations:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'airbyte-db-postgresql.airbyte.svc.cluster.local') }}"
      user: "{{ env_var('DBT_USER', 'airbyte') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: "{{ env_var('DBT_PORT', '5432') | as_number }}"
      dbname: "{{ env_var('DBT_DATABASE', 'airbyte') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'dbt_transforms') }}"
      threads: 4
      keepalives_idle: 0
      search_path: "dbt_transforms,public"
      
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'airbyte-db-postgresql.airbyte.svc.cluster.local') }}"
      user: "{{ env_var('DBT_USER', 'airbyte') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: "{{ env_var('DBT_PORT', '5432') | as_number }}"
      dbname: "{{ env_var('DBT_DATABASE', 'airbyte') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'dbt_transforms_dev') }}"
      threads: 1
      keepalives_idle: 0