global:
  serviceAccountName: airbyte
  deploymentMode: oss
  configMapName: airbyte-airbyte-env
  secretName: airbyte-airbyte-secrets
  auth:
    enabled: true
    initialUser:
      email: AIRBYTE_ADMIN_USER 
      password: AIRBYTE_ADMIN_PASSWORD

  database:
    secretName: airbyte-db-secrets
    secretValue: DATABASE_PASSWORD
    host: airbyte-db-postgresql
    port: "5432"
    database: airbyte
    user: airbyte
    password: ""  # This will be overridden by secretName/secretValue
    
  logs:
    accessKey:
      password: minio
      existingSecret: ""
      existingSecretKey: ""
    secretKey:
      password: minio123
      existingSecret: ""
      existingSecretKey: ""
  
  jobs:
    resources:
      limits:
        cpu: "2"
        memory: "4Gi"
      requests:
        cpu: "500m"
        memory: "1Gi"

webapp:
  enabled: true
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    hosts:
      - host: airbyte.thg-reporting.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: airbyte-tls
        hosts:
          - airbyte.thg-reporting.com

server:
  enabled: true
  replicaCount: 1
  env:
    - name: TRACKING_STRATEGY
      value: "segment"
    - name: AIRBYTE_VERSION
      value: "1.7.1"
    - name: CONFIG_DATABASE_USER
      value: "airbyte"
    - name: CONFIG_DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: airbyte-db-secrets
          key: DATABASE_PASSWORD
    - name: CONFIG_DATABASE_URL
      value: "jdbc:postgresql://airbyte-db-postgresql:5432/airbyte"

worker:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

workload-launcher:
  enabled: true

airbyte-bootloader:
  enabled: true
  env:
    - name: DATABASE_USER
      value: "airbyte"
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: airbyte-db-secrets
          key: DATABASE_PASSWORD
    - name: DATABASE_URL
      value: "jdbc:postgresql://airbyte-db-postgresql:5432/airbyte"

temporal:
  enabled: true
  replicaCount: 1

postgresql:
  enabled: false  # We'll use external PostgreSQL

externalDatabase:
  host: airbyte-db-postgresql
  port: 5432
  database: airbyte
  user: airbyte
  password: ""  # Will use existingSecret instead
  existingSecret: airbyte-db-secrets
  existingSecretPasswordKey: DATABASE_PASSWORD

minio:
  enabled: true
  auth:
    rootUser: minio
    rootPassword: minio123

# Resource limits
resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 1000m
    memory: 2Gi

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# This ensures all containers get proper resources for better performance
envOverrides:
  JOB_MAIN_CONTAINER_CPU_REQUEST: "500m"
  JOB_MAIN_CONTAINER_CPU_LIMIT: "2000m"
  JOB_MAIN_CONTAINER_MEMORY_REQUEST: "1Gi"
  JOB_MAIN_CONTAINER_MEMORY_LIMIT: "4Gi"
