name: 'airbyte_transformations'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'airbyte_transformations'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  airbyte_transformations:
    # Config for all files under models/
    +materialized: view
    
    staging:
      +materialized: view
      +schema: staging
      
    marts:
      +materialized: table
      +schema: marts

# Configure database schemas
vars:
  # Source schema where Airbyte loads raw data
  source_schema: 'public'
  # Target schema for transformed data
  target_schema: 'dbt_transforms'