version: 2

models:
  - name: dim_users
    description: "Cleaned and transformed user dimension table"
    columns:
      - name: user_id
        description: "Unique identifier for users"
        tests:
          - unique
          - not_null
      - name: _airbyte_ab_id
        description: "Airbyte internal ID"
      - name: created_at
        description: "User creation timestamp"
        tests:
          - not_null
      - name: updated_at
        description: "Last update timestamp"
      - name: last_synced_at
        description: "Last time data was synced from source"
      - name: data_quality_status
        description: "Data quality indicator"
        tests:
          - accepted_values:
              values: ['valid', 'missing_id', 'future_date']

  - name: dim_customers
    description: "Customer dimension with order metrics"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      - name: email
        description: "Customer email address"
        tests:
          - unique
      - name: first_name
        description: "Customer first name"
      - name: last_name
        description: "Customer last name"
      - name: customer_created_at
        description: "When customer was created"
      - name: total_orders
        description: "Total number of orders"
      - name: lifetime_value
        description: "Total amount spent by customer"
      - name: customer_status
        description: "Customer engagement status"
        tests:
          - accepted_values:
              values: ['active', 'at_risk', 'churned', 'prospect']

  - name: fact_sync_metrics
    description: "Metrics about data synchronization"
    columns:
      - name: sync_date
        description: "Date of sync"
        tests:
          - unique
          - not_null
      - name: records_synced
        description: "Number of records synced"
      - name: sync_duration_minutes
        description: "Duration of sync in minutes"