global:
  database:
    secretName: "airbyte-db-secret"
    secretValue: "password"
    host: "postgres-service.airbyte.svc.cluster.local"
    port: "5432"
    database: "airbyte"
    user: "airbyte"

webapp:
  replicaCount: 1
  service:
    type: ClusterIP
  ingress:
    enabled: true
    className: "gce"
    annotations:
      kubernetes.io/ingress.global-static-ip-name: "airbyte-ip"
      networking.gke.io/managed-certificates: "airbyte-ssl-cert"
      kubernetes.io/ingress.allow-http: "false"
    hosts:
      - host: DOMAIN_PLACEHOLDER
        paths:
          - path: /
            pathType: Prefix

server:
  replicaCount: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

worker:
  replicaCount: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

airbyte-bootloader:
  enabled: true

temporal:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "standard-rwo"
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

minio:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "standard-rwo"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

# Disable built-in PostgreSQL since we're using external one
postgresql:
  enabled: false

# Additional configurations for production readiness
metrics:
  enabled: true

logs:
  # Configure log retention
  s3:
    enabled: false
  gcs:
    enabled: false
  minio:
    enabled: true

# Security configurations
serviceAccount:
  create: true
  annotations: {}

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Network policies (optional - uncomment if needed)
# networkPolicy:
#   enabled: true
#   ingress:
#     - from: []
